CREATE TABLE sets (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT UNIQUE,
	path TEXT,
	added DATETIME NULL,
	updated DATETIME NULL
);

CREATE TABLE images (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	album_id INTEGER NOT NULL,
	name TEXT NOT NULL,
	filename TEXT NOT NULL,
	hash VARCHAR(32) NOT NULL
);

CREATE TABLE schema (
	version INTEGER
);

INSERT INTO schema VALUES(1);